language: go
go:
  - 1.x

env:
  - GO111MODULE=on

install:
  - go install github.com/onsi/ginkgo/ginkgo

script:
  - $HOME/GOPATH/bin/ginkgo -r -p --randomizeAllSpecs --failOnPending --randomizeSuites --race